# Generated by Django 6.0.7 on 2026-07-28 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='flashcards_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('choices', models.JSONField(default=list)),
                ('card_type', models.CharField(choices=[('self_assessment', 'Self assessment'), ('multiple_choice', 'Multiple choice'), ('text_input', 'Text input')], default='self_assessment', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('search_terms', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_interval_ms', models.BigIntegerField(default=0)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(choices=[('very_hard', 'Very hard'), ('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy'), ('very_easy', 'Very easy')], default='medium', max_length=10)),
                ('categories', models.ManyToManyField(blank=True, related_name='flashcards', to='flashcards_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'parent'], name='flashcards__user_id_88c7ab_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'due_date'], name='flashcards__user_id_281944_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', '-created_at'], name='flashcards__user_id_69b665_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'last_interval_ms'], name='flashcards__user_id_15afe5_idx'),
        ),
    ]
