# Generated by Django 6.0.7 on 2026-07-30 21:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flashcards_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_correct', models.BooleanField()),
                ('last_interval_ms', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='flashcards_app.category')),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='flashcards_app.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['last_interval_ms', 'was_correct'], name='learn_app_l_last_in_3db7bf_idx'), models.Index(fields=['category', '-created_at'], name='learn_app_l_categor_96960b_idx'), models.Index(fields=['flashcard', '-created_at'], name='learn_app_l_flashca_d8a8e1_idx'), models.Index(fields=['user', '-created_at'], name='learn_app_l_user_id_6c6841_idx')],
            },
        ),
    ]
